// Generated by gencpp from file odometry/CarState.msg
// DO NOT EDIT!


#ifndef ODOMETRY_MESSAGE_CARSTATE_H
#define ODOMETRY_MESSAGE_CARSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odometry
{
template <class ContainerAllocator>
struct CarState_
{
  typedef CarState_<ContainerAllocator> Type;

  CarState_()
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  CarState_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::odometry::CarState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometry::CarState_<ContainerAllocator> const> ConstPtr;

}; // struct CarState_

typedef ::odometry::CarState_<std::allocator<void> > CarState;

typedef boost::shared_ptr< ::odometry::CarState > CarStatePtr;
typedef boost::shared_ptr< ::odometry::CarState const> CarStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometry::CarState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometry::CarState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::odometry::CarState_<ContainerAllocator1> & lhs, const ::odometry::CarState_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::odometry::CarState_<ContainerAllocator1> & lhs, const ::odometry::CarState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace odometry

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::odometry::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometry::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometry::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::CarState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::CarState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometry::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39617ea5ffa910b78cdf07b659b77ce4";
  }

  static const char* value(const ::odometry::CarState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39617ea5ffa910b7ULL;
  static const uint64_t static_value2 = 0x8cdf07b659b77ce4ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometry::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometry/CarState";
  }

  static const char* value(const ::odometry::CarState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometry::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 angle\n"
;
  }

  static const char* value(const ::odometry::CarState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometry::CarState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometry::CarState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometry::CarState_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETRY_MESSAGE_CARSTATE_H
